---
build_from:
  aarch64: 'ghcr.io/hassio-addons/base:18.0.0'
  armv7: 'ghcr.io/hassio-addons/base:18.0.0'
  amd64: 'ghcr.io/hassio-addons/base:18.0.0'
  armhf: 'ghcr.io/hassio-addons/base:18.0.0'
  i386: 'ghcr.io/hassio-addons/base:18.0.0'
args:
  RUSTDESK_SERVER_VERSION: 1.1.14
codenotary:
  base_image: notary@home-assistant.io
  signer: codenotary@jbelascoain.dev